Update patch set 4
Patch Set 4:

compiler update causes build error
error: unknown warning option '-Wno-tautological-constant-compare'; did you mean '-Wno-tautological-pointer-compare'? [-Werror,-Wunknown-warning-option]

which comes from third_party/libxmp/BUILD.gn and build/config/compiler/BUILD.gn

manually removing the option from those files, the library builds and passes.

Patch-set: 4
Reviewer: Gerrit User 1115898 <1115898@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0