Update patch set 3
Patch Set 3:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 1161509: Patch set ref refs/changes/09/1161509/3 not found. Expected patch set ref of 3 to point to revision 45689c72c3f462a1f4584c61e7adbf0d67ebcb7e

Patch-set: 3
Tag: autogenerated:cq:full-run