Update patch set 4
Patch Set 4:

This is failing on windows.
[ RUN      ] LibYUVConvertTest.J444ToABGR_ARGB_Any
../../unit_test/convert_test.cc(2603): error: Expected equality of these values:
  dst_argb_c[i + 0]
    Which is: '\xD1' (209)
  dst_argb_bc[i + 0]
    Which is: '\xF6' (246)

but upstream its passing both windows and asan.  Currently win32 does use row_win.cc which differs from row_gcc.cc and unittests should account for that when necessary, or row.h can disable row_win.cc functions.

Patch-set: 4
Reviewer: Gerrit User 1115898 <1115898@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>