Update patch set 3
Patch Set 3:

Visual C did not accept this line:
#if defined(__linux__) || (defined(__clang__) && __has_include(<pthread.h>))

FAILED: obj/libyuv_unittest/cpu_thread_test.obj 
ninja -t msvc -e environment.x86 -- E:\b\build\slave\cache\goma_client/gomacc.exe "E:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64_x86/cl.exe" /nologo /showIncludes /FC @obj/libyuv_unittest/cpu_thread_test.obj.rsp /c ../../unit_test/cpu_thread_test.cc /Foobj/libyuv_unittest/cpu_thread_test.obj /Fd"obj/libyuv_unittest_cc.pdb"
e:\b\build\slave\win\build\src\unit_test\cpu_thread_test.cc(15): fatal error C1012: unmatched parenthesis: missing ')'
[43/49] CXX obj/libyuv_unittest/basictypes_test.obj

Patch-set: 3
Reviewer: Gerrit User 1115898 <1115898@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>