Update patch set 2
Patch Set 2:

The errors are related to the ar tool (archiver) used when building yasm, which is used for jpeg_turbo

FAILED: obj/third_party/yasm/libyasm_utils.a 
python "../../build/toolchain/gcc_ar_wrapper.py"  --output=obj/third_party/yasm/libyasm_utils.a --ar="../../third_party/llvm-build/Release+Asserts/bin/llvm-ar"  rcsD @"obj/third_party/yasm/libyasm_utils.a.rsp"
Traceback (most recent call last):
  File "../../build/toolchain/gcc_ar_wrapper.py", line 66, in <module>
    sys.exit(main())
  File "../../build/toolchain/gcc_ar_wrapper.py", line 62, in main
    return subprocess.call(wrapper_utils.CommandToRun(command))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ar is a 'bin util' provided by gcc.
It looks like we are transitioning to llvm-ar, which is provided by llvm, for use by clang tool chains.

Patch-set: 2
Reviewer: Gerrit User 1115898 <1115898@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>